### ISSUE TITLE
Add support for using personal access token accessing Jira Data Center

### ISSUE THREAD

**Issue by christofferholmstedt** [dstengele/python-insight#14]
During the last year Atlassian added support to Jira Data Center for using Personal Access Tokens to access Jira API instead of basic auth with username and password. It has been available in cloud for some time and basic auth with username and password is not allowed for the cloud anymore.

Related to this library the [pycontribs/jira](https://github.com/pycontribs/jira) library does not support PAT login but can be fixed in local script/application by just changing the HTTP headers. Workaround/solution available in a comment by skaiaa at https://github.com/pycontribs/jira/issues/989#issuecomment-772683446 a pull request is available at https://github.com/pycontribs/jira/pull/991 but is blocked by continuous integration infrastructure issues tracked in https://github.com/pycontribs/jira/issues/896

I just had a few minutes in June to look into how to solve this with the python-insight library but couldn't find any straight forward solution. I will look at it again in August/September and filing this issue so others can come with suggestions in advance on how to best solve this. If it is possible already today I'm happy with such an answer as well ;)

**Notes**
- [Jira Data Center and Jira Cloud have different APIs when it comes to login with Personal Access Token.](https://github.com/pycontribs/jira/issues/993#issue-782130582)

**Comment by studioj** [comment]
Thanks for your report would this be a possible solution? https://github.com/pycontribs/jira/pull/991

Dont hesitate to comment or contribute 👍

**Comment by dstengele** [comment]
I have just released a new version that splits the auth logic in multiple parameters. One of them is token_auth which takes the token as a String and uses it as the Bearer token. This works with the DC PATs.
