### ISSUE TITLE
InsightObjectAttributes: ValueError: Date and Date Time attributes have hardcoded format

### ISSUE THREAD

**Issue by christofferholmstedt** [dstengele/python-insight#6]
When accessing insight object with insight attribute of type Date (and Date Time) the request for the attribute value will raise ValueError when format is not correct.

```
File "<path>\venv\lib\site-packages\jira_insight\insight.py", line 203, in value
    return datetime.datetime.strptime(
  File "<path>\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "<path>\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021-01-13' does not match format '%d.%m.%Y'
```

Line [204](https://github.com/schuppentier/python-insight/blob/a64c166593538a6172ae2746a8837a59c8948e28/jira_insight/insight.py#L204) and [208](https://github.com/schuppentier/python-insight/blob/a64c166593538a6172ae2746a8837a59c8948e28/jira_insight/insight.py#L208) in insight.py have hardcoded date format.

Not sure what the best solution is but I assume it is better to just return the raw string and skip the datetime parsing within the script there, so the user can define the proper format for parsing date/datetime.

**Comment by dstengele** [comment]
Sorry for the late response. I have recently looked into this and it looks like Insight is using the Jira date format for its API. I think it would be best to automatically get the date format from Jira somehow and then use that to parse the date(time) strings but I have not yet found a good way to do that.

So for the time being I will merge #7 and create a new issue to enhance the date parsing.

**Comment by dstengele** [comment]
See #9

**Comment by christofferholmstedt** [comment]
Thanks for the update. I'm not so quick myself ;)
I will verify that v0.5.0 works next week and can close this issue by then.

**Comment by christofferholmstedt** [comment]
I have verified that the v0.5.0|1 works during June. Closing.
